name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: backend-maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            backend-maven-${{ runner.os }}-

      - name: Build Backend
        run: |
          cd Backend
          mvn clean package -B

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: Backend/target/*.jar

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: MD/node_modules
          key: md-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            md-node-modules-${{ runner.os }}-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build Frontend
        run: |
          cd MD
          npm install
          npm run build

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: MD/dist/

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: backend-maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            backend-maven-${{ runner.os }}-

      - name: Run Backend Tests
        run: |
          cd Backend
          mvn test -B

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: MD/node_modules
          key: md-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            md-node-modules-${{ runner.os }}-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and run Frontend Tests
        run: |
          cd MD
          npm install
          npm test